language: cpp
dist: focal # 20.04; bionic: 18.04, xenial: 16.04
compiler:
  - clang
  - gcc

addons:
  apt:
    packages:
    - g++
    - clang

install:
- if [ "$CXX" = "g++" ]; then export CXX="g++" CC="gcc"; fi
- if [ "$CXX" = "clang++" ]; then export CXX="clang++" CC="clang" LD_LIBRARY_PATH=/usr/local/clang/lib:$LD_LIBRARY_PATH ; fi

# command to run tests
script: 
  - wget https://cmake.org/files/v3.9/cmake-3.9.2-Linux-x86_64.sh
  - sudo sh cmake-3.9.2-Linux-x86_64.sh -- --skip-license --prefix=/usr
  - git submodule update --init
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=Release
  - cmake --build . --config Release
  - ./ChebToolsCatchTests

notifications:
  email:
    recipients:
      - ian.bell@nist.gov
    on_success: never # default: change
    on_failure: always # default: always
