name: build and run Catch tests
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: checkout submodules
      run: git submodule update --init --recursive
    - name: mkdir
      run: mkdir build && cd build
    - name: cmake config
      run: cd build && cmake .. -DCMAKE_BUILD_TYPE=Release
    - name: cmake make
      run: cmake --build build --target ChebToolsCatchTests
    # run tests
    - name: run Catch tests
      run: build/ChebToolsCatchTests
    - name: build python interface
      run: python setup.py build

